apiVersion: v1
kind: Service
metadata:
  name: couchbase-connector
  namespace: connectors
spec:
  selector:
    app: couchbase-connector
  ports:
    - name: http
      port: 8080
      targetPort: http
  type: ClusterIP
